name       : openpaperwork-gtk
version    : 2.1.0
release    : 2
source     :
    - https://pypi.io/packages/source/o/openpaperwork-gtk/openpaperwork-gtk-2.1.0.tar.gz : c59d7692b27b894c0230399bd2d16d79d6350021a36fcd3db347fd2dc8552fa3
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : programming.python
summary    : OpenPaperWork GTK plugins
description: |
    Paperwork is a GUI to make papers searchable. A bunch of plugins for Paperwork related to GLib and GTK.
builddeps  :
    - openpaperwork-core
    - python-gobject
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
