name       : openpaperwork-gtk
version    : 2.1.1
release    : 4
source     :
    - https://pypi.io/packages/source/o/openpaperwork-gtk/openpaperwork-gtk-2.1.1.tar.gz : dce2933fd3b0214ad68d8e6f224da579d68e89ca9f2fa27c504a7ce6149a55c3
homepage   : https://openpaper.work/
license    : GPL-3.0-or-later
component  : programming.python
summary    : OpenPaperWork GTK plugins
description: |
    Paperwork is a GUI to make papers searchable. A bunch of plugins for Paperwork related to GLib and GTK.
builddeps  :
    - openpaperwork-core
    - python-gobject
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
